config/routes.rb
Rails.application.routes.draw do
  get "tasks", to: "tasks#index"

  get "tasks/new", to: "tasks#new", as: :new_task
  post "tasks", to: "tasks#create"

  get "tasks/:id/edit", to: "tasks#edit", as: :edit_task
  patch "tasks/:id", to: "tasks#update"

  get "tasks/:id", to: "tasks#show", as: :task

  delete "tasks/:id", to: "tasks#destroy"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

before_action :find_task, only: [:show, :edit, :update, :destroy]

  def index       # GET /tasks
    @tasks = Task.all
  end

  def show    # GET /tasks/:id
  end

  def new         # GET /tasks/new
    @task = Task.new
  end

  def create     # POST /tasks
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path
  end

  def edit       # GET /tasks/:id/edit
  end

  def update      # PATCH /tasks/:i
    @task.update(task_params2)
    redirect_to tasks_path
  end

  def destroy     # DELETE /tasks/:id
    @task.destroy
    redirect_to tasks_path
  end

private

def find_task
  @task = Task.find(params[:id])
end

def task_params
  params.require(:task).permit(:title, :details)
end

def task_params2
  params.require(:task).permit(:title, :details, :completed)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
  def task_adapted
    if @task.completed
      "This task is completed"
    else
      "This task is not completed yet"
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar">
      <%= link_to "Return to task list", tasks_path, class: "link" %>
      <%= link_to "Add a new task", new_task_path, class: "link"  %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit task</h1>

<div class="container-new">
  <%= form_for(@task) do |f| %>

    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :details %>
      <%= f.text_field :details, class: 'form-control' %>
    </div>

    <div class="form-group">
      <input type="checkbox" id="task_check" name="task[completed]" value="task" <%= "checked" if @task.completed%>>
      <label for="checkbox">Completed</label>
    </div>

    <%= f.submit class: 'btn btn-primary btn-sm' %>
  <% end %>
</div>

app/views/tasks/index.html.erb
<h1>My tasks</h1>

<% @tasks.each do |task| %>
  <div class="task_listed">
    <input type="checkbox" id="checkbox" name="interest" value="task" <%= "checked" if task.completed%>>
    <label for="checkbox"><%= link_to task.title, task_path(task) %></label>
    <%= link_to task_path(task), method: :delete, data: { confirm: "Are you sure?" } do %>
      <i class="fas fa-trash-alt"></i>
    <% end %>
  </div>
<% end %>


<p><%= link_to "Add a new task", new_task_path, class: "link" %></p>

app/views/tasks/new.html.erb
<h1>New task</h1>

<div class="container-new">
  <%= form_for(@task) do |f| %>

    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :details %>
      <%= f.text_field :details, class: 'form-control' %>
    </div>

    <%= f.submit class: 'btn btn-primary btn-sm' %>
  <% end %>
</div>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>

<div class="container-show">
  <p class="task-detail"><%= @task.details %></p>
    <div class="task-div">
      <input type="checkbox" id="checkbox" name="interest" value="task" <%= "checked" if @task.completed%>>
      <label for="checkbox"><%= task_adapted %></label>
    </div>
</div>

<button type="button" class="btn btn-outline-danger"><%= link_to "Edit this task", edit_task_path(@task), class: "link" %></button>